# Generated by Django 5.2.1 on 2025-05-26 11:16

from django.db import migrations, models

from pathlib import Path

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
# d:\G33\1_PYTHON\Django_Project\project\project\settings.py
# ...
BASE_DIR = Path(__file__).resolve().parent.parent
# ...
STATICFILES_DIRS = [
    BASE_DIR / "static", # Для общих статических файлов проекта
    # '/var/www/static',
]
